#### 仅用于代码块的测试

In [19]:
import numpy as np
import random

In [20]:
X_sensitive = np.array([0.85, 2450.0, 12.7, 0.23, 0.05, 0.02, 0.01, 0.03, 0.04, 0.06])  # 目标数据

shadow_data = []
for _ in range(5):
        # 添加随机噪声来创建影子样本
        noise = np.random.normal(0, 0.05, X_sensitive.shape)
        shadow_sample = X_sensitive + noise
        # 确保数据在有效范围内（例如，地形特征值非负）
        shadow_sample = np.clip(shadow_sample, 0, None)
        shadow_data.append(shadow_sample)
X_shadow = np.array(shadow_data)
X_shadow

array([[8.86701435e-01, 2.45000089e+03, 1.26409169e+01, 2.30114480e-01,
        6.39222469e-02, 0.00000000e+00, 1.51924096e-02, 5.38487478e-02,
        0.00000000e+00, 7.75175914e-02],
       [8.74766221e-01, 2.44990820e+03, 1.27615331e+01, 2.49215083e-01,
        7.02117072e-02, 0.00000000e+00, 8.17864685e-03, 0.00000000e+00,
        3.09482891e-02, 4.94204922e-02],
       [7.55503275e-01, 2.44995854e+03, 1.27665168e+01, 2.55454888e-01,
        2.93540507e-02, 0.00000000e+00, 0.00000000e+00, 9.18140624e-03,
        2.64005607e-02, 8.70662703e-03],
       [8.91199096e-01, 2.45004416e+03, 1.27321179e+01, 2.34228373e-01,
        1.04606670e-01, 5.16245889e-02, 1.32634704e-02, 4.26630559e-02,
        7.87918486e-02, 9.04497184e-02],
       [9.01170682e-01, 2.44996203e+03, 1.26907885e+01, 1.88610657e-01,
        9.77506359e-02, 0.00000000e+00, 6.31593227e-02, 5.88140858e-03,
        5.07890425e-02, 4.05178089e-02]])

In [21]:
X_candidate = np.vstack([X_sensitive.reshape(1, -1), X_shadow])   # 数组的拼接操作
X_candidate

array([[8.50000000e-01, 2.45000000e+03, 1.27000000e+01, 2.30000000e-01,
        5.00000000e-02, 2.00000000e-02, 1.00000000e-02, 3.00000000e-02,
        4.00000000e-02, 6.00000000e-02],
       [8.86701435e-01, 2.45000089e+03, 1.26409169e+01, 2.30114480e-01,
        6.39222469e-02, 0.00000000e+00, 1.51924096e-02, 5.38487478e-02,
        0.00000000e+00, 7.75175914e-02],
       [8.74766221e-01, 2.44990820e+03, 1.27615331e+01, 2.49215083e-01,
        7.02117072e-02, 0.00000000e+00, 8.17864685e-03, 0.00000000e+00,
        3.09482891e-02, 4.94204922e-02],
       [7.55503275e-01, 2.44995854e+03, 1.27665168e+01, 2.55454888e-01,
        2.93540507e-02, 0.00000000e+00, 0.00000000e+00, 9.18140624e-03,
        2.64005607e-02, 8.70662703e-03],
       [8.91199096e-01, 2.45004416e+03, 1.27321179e+01, 2.34228373e-01,
        1.04606670e-01, 5.16245889e-02, 1.32634704e-02, 4.26630559e-02,
        7.87918486e-02, 9.04497184e-02],
       [9.01170682e-01, 2.44996203e+03, 1.26907885e+01, 1.88610657e-01,
   

In [22]:
y_candidate = np.array([1] + [0] * len(X_shadow))
y_candidate

array([1, 0, 0, 0, 0, 0])

In [23]:
for i, x in enumerate(X_candidate):
    print(f"样本 {i}: {x}")

样本 0: [8.50e-01 2.45e+03 1.27e+01 2.30e-01 5.00e-02 2.00e-02 1.00e-02 3.00e-02
 4.00e-02 6.00e-02]
样本 1: [8.86701435e-01 2.45000089e+03 1.26409169e+01 2.30114480e-01
 6.39222469e-02 0.00000000e+00 1.51924096e-02 5.38487478e-02
 0.00000000e+00 7.75175914e-02]
样本 2: [8.74766221e-01 2.44990820e+03 1.27615331e+01 2.49215083e-01
 7.02117072e-02 0.00000000e+00 8.17864685e-03 0.00000000e+00
 3.09482891e-02 4.94204922e-02]
样本 3: [7.55503275e-01 2.44995854e+03 1.27665168e+01 2.55454888e-01
 2.93540507e-02 0.00000000e+00 0.00000000e+00 9.18140624e-03
 2.64005607e-02 8.70662703e-03]
样本 4: [8.91199096e-01 2.45004416e+03 1.27321179e+01 2.34228373e-01
 1.04606670e-01 5.16245889e-02 1.32634704e-02 4.26630559e-02
 7.87918486e-02 9.04497184e-02]
样本 5: [9.01170682e-01 2.44996203e+03 1.26907885e+01 1.88610657e-01
 9.77506359e-02 0.00000000e+00 6.31593227e-02 5.88140858e-03
 5.07890425e-02 4.05178089e-02]


In [30]:
attack_features = [] # 用于训练攻击模型的特征
attack_labels = []   # 对应的标签（1=成员，0=非成员）

for i, x in enumerate(X_candidate):
    feature_vector = [random.random(),random.randint(0,6)]

    attack_features.append(feature_vector)
    attack_labels.append(y_candidate[i])

print(attack_features)
print(attack_labels)

[[0.6454266436357916, 2], [0.02655585065469701, 0], [0.46948186235798517, 4], [0.4035600385249586, 1], [0.258408801386785, 0], [0.6638772656537173, 0]]
[1, 0, 0, 0, 0, 0]


In [31]:
attack_features = np.array(attack_features)
attack_labels = np.array(attack_labels)

print(attack_features)
print(attack_labels)

[[0.64542664 2.        ]
 [0.02655585 0.        ]
 [0.46948186 4.        ]
 [0.40356004 1.        ]
 [0.2584088  0.        ]
 [0.66387727 0.        ]]
[1 0 0 0 0 0]


In [33]:
from sklearn.ensemble import RandomForestClassifier

# 使用一个简单的分类器，如随机森林
attack_model = RandomForestClassifier(n_estimators=50, random_state=42)  # 树的数量50, 随机种子42 分类器
attack_model.fit(attack_features, attack_labels)  # 训练攻击模型

RandomForestClassifier(n_estimators=50, random_state=42)

In [ ]:
# 我这里有一个疑问：如果sensitive_feature还是训练时那个值，而且当时标签给的也是1，
# 现在再用该模型进行预测的话，肯定也会返回1啊，这算自欺欺人吗？
sensitive_feature = [0.64542664,2]
membership_score = attack_model.predict_proba([sensitive_feature])[0][1] # 属于类别1（成员）的概率
membership_score

0.74

### train_lstm_model2.py过程中部分函数测试

JSON string经过json.load()方法将被解码成Python Object。
Python 编码为 JSON 类型转换对应表：

    JSON 	        Python
    
    object 	        dict
    array 	        list
    string 	        str
    number (int) 	int
    number (real) 	float
    true 	        True
    false 	        False
    null 	        None

In [17]:
import json

file_path = './LSTM/generated_data/lstm_feature_data.json'
with open(file_path, 'r') as f:
        data = json.load(f)  # 序列化加载json文件,返回一个dict对象

data.__class__  # dict

dict

Python 字典 items() 方法以列表返回视图对象，是一个可遍历的key/value 对。

dict.keys()、dict.values() 和 dict.items() 返回的都是视图对象（ view objects），提供了字典实体的动态视图，这就意味着字典改变，视图也会跟着变化。

视图对象不是列表，不支持索引，可以使用 list() 来转换为列表。
我们不能对视图对象进行任何的修改，因为字典的视图对象都是只读的。

In [10]:
for keys,values in data.items():  
    print(keys,values)

185272c249 {'task_id': '185272c249', 'is_malicious': True, 'global_features': {'attack_model_trained': True, 'total_query_count': 166, 'final_output_size_bytes': 80}, 'sequence': [{'timestep': 0, 'response_confidence': 0.9744, 'time_delta_since_last_query': 0.0, 'distance_from_anchor_vector': 0.1752}, {'timestep': 1, 'response_confidence': 0.6107, 'time_delta_since_last_query': 0.1707, 'distance_from_anchor_vector': 0.2463}, {'timestep': 2, 'response_confidence': 0.4074, 'time_delta_since_last_query': 0.2229, 'distance_from_anchor_vector': 0.3002}, {'timestep': 3, 'response_confidence': 0.5373, 'time_delta_since_last_query': 0.1805, 'distance_from_anchor_vector': 0.1801}, {'timestep': 4, 'response_confidence': 0.5503, 'time_delta_since_last_query': 0.0838, 'distance_from_anchor_vector': 0.2939}, {'timestep': 5, 'response_confidence': 0.4883, 'time_delta_since_last_query': 0.1594, 'distance_from_anchor_vector': 0.2459}, {'timestep': 6, 'response_confidence': 0.4655, 'time_delta_since_la

#### enumerate() 方法的语法

enumerate() 函数用于将一个可遍历的数据对象(如列表、元组或字符串)组合为一个索引序列，同时列出数据和数据下标，一般用在 for 循环当中。

In [20]:
seq = ['one', 'two', 'three']
for i, element in enumerate(seq):
    print(i, element)

0 one
1 two
2 three


#### 截断与填充测试

In [55]:
import numpy as np

padded = np.full((3,2,3), 0, dtype=np.float32)  # 返回一个（2,2,3）且类型为float32的三维数组，并用0填充
# padded = np.zeros((3,2,3))
padded


array([[[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]]], dtype=float32)

In [56]:
sequences = [
    np.array([[1, 2, 3], [4, 5, 6]]),
    np.array([[7, 8, 9]]),
    np.array([[10, 11, 12], [13, 14, 15], [16, 17, 18]]),
]  # 每个序列的长度不同

sequences

[array([[1, 2, 3],
        [4, 5, 6]]),
 array([[7, 8, 9]]),
 array([[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]])]

In [41]:
sequences[0]  # 第一个序列

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
maxlen = 2  # 最大序列长度
for i, seq in enumerate(sequences):  # sequences是个list、每一个seq是个numpy二维数组
    print(f"序列 {i} 的原始形状{seq.shape}")  # 打印每个数组的形状（长度，特征数）
    trunc = seq[:maxlen]  # 截断序列，保留前maxlen个元素
    print(f"序列 {i} 的截断后的形状为{trunc.shape}")  # 打印截断后的数组形状（长度，特征数）

序列 0 的原始形状(2, 3)
序列 0 的截断后的形状为(2, 3)
序列 1 的原始形状(1, 3)
序列 1 的截断后的形状为(1, 3)
序列 2 的原始形状(3, 3)
序列 2 的截断后的形状为(2, 3)


In [67]:
seq = np.array([[7, 8, 9]])  # (1, 3)的二维数组

print(seq[:1,:])
print(seq[:2,:]) 
print(seq[:3,:])  # 经过测试发现，对于一个(1, 3)的二维数组，只能取第一行的3个元素

[[7 8 9]]
[[7 8 9]]
[[7 8 9]]


In [ ]:
maxlen = 2
for i, seq in enumerate(sequences):  # sequences是个list、每一个seq是个numpy二维数组
    trunc = seq[:maxlen]  # 截断序列，保留前maxlen个元素
    padded[i, :len(trunc)] = trunc  # 填充到padded三维数组中

padded

array([[[ 1.,  2.,  3.],
        [ 4.,  5.,  6.]],

       [[ 7.,  8.,  9.],
        [ 0.,  0.,  0.]],

       [[10., 11., 12.],
        [13., 14., 15.]]], dtype=float32)

#### TensorDataset
用于将多个张量(tensors)包装成一个数据集。它要求所有张量的第一个维度（样本数量维度）大小相同。

In [ ]:
import torch
from torch.utils.data import TensorDataset, DataLoader

# 创建示例数据
X = torch.randn(100, 5)  # 100个样本，每个样本5个特征
y = torch.randint(0, 2, (100,))  # 100个标签

# 创建TensorDataset
dataset = TensorDataset(X, y)

print(dataset.__class__)
dataset.__dict__  # 返回dataset的属性字典

<class 'torch.utils.data.dataset.TensorDataset'>


{'tensors': (tensor([[ 0.7923, -1.7662, -0.6132, -0.4954, -0.2939],
          [-0.1820,  0.7619,  0.9493,  1.6349, -0.7141],
          [-1.2271, -1.4759,  0.5162,  0.3601,  0.3544],
          [-0.7038, -0.2166, -0.4250, -1.1546,  0.2131],
          [-0.9184,  0.0910, -0.0207,  1.5959, -0.9602],
          [ 2.7021, -2.4142, -0.4476,  2.2584, -0.5519],
          [ 0.3645, -0.4261, -0.5753,  1.3640, -3.2470],
          [ 1.1197, -1.4577,  2.0719, -0.5900,  0.3957],
          [ 1.9609, -0.0719,  0.2686,  0.8026,  0.6438],
          [-0.0841, -0.5944, -1.0858, -1.4938,  1.3181],
          [ 0.6452,  0.2802, -0.2243,  0.4935,  1.7486],
          [ 1.2802,  0.4116, -0.1317, -0.3940, -0.3439],
          [-0.3887, -1.1547, -1.1251,  0.2180,  0.2319],
          [-0.8387,  1.4208, -0.2836,  0.9205,  0.6284],
          [-1.9533, -1.9604, -0.3190, -0.8186, -1.9088],
          [ 1.1352,  1.3316,  0.8931,  0.6329, -1.0728],
          [-0.4268, -0.3010, -1.0460,  0.2533,  2.2758],
          [ 0.3002, 

In [28]:
# 访问单个样本
print(dataset[0])  # 返回 (特征张量, 标签)

(tensor([ 0.7923, -1.7662, -0.6132, -0.4954, -0.2939]), tensor(1))


In [31]:
print(dataset[0][0])

tensor([ 0.7923, -1.7662, -0.6132, -0.4954, -0.2939])


In [32]:
print(dataset[0][1])

tensor(1)


In [35]:
print(dataset[99])  # 返回 (特征张量, 标签)

(tensor([0.8198, 0.8158, 0.2360, 1.4075, 1.0501]), tensor(1))


In [26]:
# 结合DataLoader使用
dataloader = DataLoader(dataset, batch_size=32, shuffle=True)

for batch_X, batch_y in dataloader:
    print(f"Batch X shape: {batch_X.shape}")  # torch.Size([32, 5])
    print(f"Batch y shape: {batch_y.shape}")  # torch.Size([32])

Batch X shape: torch.Size([32, 5])
Batch y shape: torch.Size([32])
Batch X shape: torch.Size([32, 5])
Batch y shape: torch.Size([32])
Batch X shape: torch.Size([32, 5])
Batch y shape: torch.Size([32])
Batch X shape: torch.Size([4, 5])
Batch y shape: torch.Size([4])


#### TensorDataset vs Dataset  
    特性	        TensorDataset	    自定义Dataset
    实现复杂度      简单，一行代码	        需要实现__len__和__getitem__
    灵活性	        低，只能处理张量	    高，可以处理任何数据类型
    数据预处理      需要在创建前完成	    可以在__getitem__中动态处理
    适用场景	    数据已经是张量形式	    复杂的数据加载和预处理

    TensorDataset：适合数据已经是张量形式的简单场景，使用方便
    自定义Dataset：适合需要复杂数据处理、数据增强或非张量数据的场景

### LSTM核心参数 + 输入输出的研究

#### 大前提：处理等长的序列

#### 1.单层单向LSTM

In [4]:
import torch
import torch.nn as nn

# 定义参数
input_size = 3   # 每个时间步输入特征维度为3
seq_len = 150       # 序列长度为150
batch_size = 16    # 批次大小为16
hidden_size = 64  # 隐藏层特征维度为64
num_layers = 1    # 一层LSTM
num_directions = 1 # 单向，方向数为1

# 创建单层单向LSTM
lstm = nn.LSTM(input_size, hidden_size, num_layers)

# 准备输入数据 input(序列长度, 批次大小, 输入特征维度)
input = torch.randn(seq_len, batch_size, input_size)  # (150,16,3)
# 初始化隐藏状态和细胞状态  h0,c0(层数×方向数, 批次大小, 隐藏维度)
h0 = torch.randn(num_layers * num_directions, batch_size, hidden_size)  # (1*1,16,64)
c0 = torch.randn(num_layers * num_directions, batch_size, hidden_size)

# 前向传播 output(序列长度, 批次大小, 隐藏维度×方向数)
output, (hn, cn) = lstm(input, (h0, c0))

print(f"单层单向LSTM:")
print(f"output shape: {output.shape}") # (150, 16, 64)
print(f"hn shape: {hn.shape}")         # (1, 16, 64)
print(f"cn shape: {cn.shape}")         # (1, 16, 64)
# 验证 output[-1] == hn[-1]
print(torch.allclose(output[-1], hn[-1])) # 应为 True

单层单向LSTM:
output shape: torch.Size([150, 16, 64])
hn shape: torch.Size([1, 16, 64])
cn shape: torch.Size([1, 16, 64])
True


#### batch_first=True
如果再将batch_first=True, 则输入数据为 (batch_size, seq_len, input_size)


In [13]:
# 创建单层单向LSTM (batch_first=True)
lstm = nn.LSTM(input_size, hidden_size, num_layers,batch_first=True)  # 将batch之前，更加符合直观习惯

# 准备输入数据 input(批次大小, 序列长度, 输入特征维度)
input = torch.randn(batch_size, seq_len, input_size)  # (16,150,3)
# 初始化隐藏状态和细胞状态 h0,c0(层数×方向数, 批次大小, 隐藏维度)
h0 = torch.randn(num_layers * num_directions, batch_size, hidden_size)  # (1*1,16,64)
c0 = torch.randn(num_layers * num_directions, batch_size, hidden_size)

# 前向传播  output(批次大小, 序列长度, 隐藏维度×方向数)
output, (hn, cn) = lstm(input, (h0, c0))

print(f"单层单向LSTM:")
print(f"output shape: {output.shape}") # (16, 150, 64)
print(f"hn shape: {hn.shape}")         # (1, 16, 64)
print(f"cn shape: {cn.shape}")         # (1, 16, 64)

# 验证 output 的最后一个时间步与 hn 的最后一层相同
print(torch.allclose(output[:, -1, :], hn[-1])) # 应为 True

单层单向LSTM:
output shape: torch.Size([16, 150, 64])
hn shape: torch.Size([2, 16, 64])
cn shape: torch.Size([2, 16, 64])
True


#### 总结：
【前提：batch_first=True】
output,(hn,cn) = lstm(input,(h0,c0))

    由于
    output(序列长度, 批次大小, 隐藏维度×方向数)：返回最后一层，所有时间步的隐藏状态
    hn(层数×方向数, 批次大小, 隐藏维度)：返回所有层的最后一个时间步的隐藏状态

所以在单层单向LSTM中，输出的最后一个时间步与隐藏状态的最后一层相同。即：
    output[:,-1,:] = hn[-1,:,:] = hn[0]

    1.batch_first只会影响input、output的维度,而不会影响h0、c0、hn、cn这些隐藏状态和细胞状态的维度。


#### 2.两层单向LSTM
多层LSTM通过堆叠多个LSTM层来提取更深层的序列特征，上一层的输出作为下一层的输入

In [26]:
import torch
import torch.nn as nn

# 定义参数
input_size = 3   # 每个时间步输入特征维度为3
seq_len = 150       # 序列长度为150
batch_size = 16    # 批次大小为16
hidden_size = 64  # 隐藏层特征维度为64
num_layers = 2    # 两层LSTM
num_directions = 1 # 单向，方向数为1

# 创建多层单向LSTM
lstm = nn.LSTM(input_size, hidden_size, num_layers)  # batch_first默认为False

# 准备输入数据 input(序列长度, 批次大小, 输入特征维度)
input = torch.randn(seq_len, batch_size, input_size)  # (150,16,3)
# 初始状态 h0,c0(层数×方向数, 批次大小, 隐藏维度)
h0 = torch.randn(num_layers * num_directions, batch_size, hidden_size)  # (2*1,16,64)
c0 = torch.randn(num_layers * num_directions, batch_size, hidden_size)

# 前向传播  output(序列长度, 批次大小, 隐藏维度×方向数)
output, (hn, cn) = lstm(input, (h0, c0))

print(f"\n多层单向LSTM:")
print(f"output shape: {output.shape}") # (150, 16, 64*1) # 注意：output仍是最后一层的输出
print(f"hn shape: {hn.shape}")         # (2, 16, 64) # 两层最后时间步的隐藏状态
print(f"cn shape: {cn.shape}")         # (2, 16, 64)

# 验证 output 的最后一个时间步与 hn 的最后一层相同
print(f"output[-1,:,:] == hn[-1]: {torch.allclose(output[-1,:,:], hn[-1])}")



多层单向LSTM:
output shape: torch.Size([150, 16, 64])
hn shape: torch.Size([2, 16, 64])
cn shape: torch.Size([2, 16, 64])
output[-1,:,:] == hn[-1]: True


#### batch_first=True
如果再将batch_first=True, 则输入数据为 (batch_size, seq_len, input_size),输出为 (batch_size, seq_len, hidden_dim*num_directions)

In [15]:
# 创建多层单向LSTM (batch_first=True)
lstm = nn.LSTM(input_size, hidden_size, num_layers, batch_first=True)

# 准备输入数据 input(批次大小, 序列长度, 输入特征维度)
input = torch.randn(batch_size, seq_len, input_size)  # (16,150,3)
# 初始化隐藏状态和细胞状态 h0,c0(层数×方向数, 批次大小, 隐藏维度)
h0 = torch.randn(num_layers * num_directions, batch_size, hidden_size)  # (2*1, 16, 20)
c0 = torch.randn(num_layers * num_directions, batch_size, hidden_size)

# output(批次大小, 序列长度, 隐藏维度×方向数)
output, (hn, cn) = lstm(input, (h0, c0))

print(f"\n多层单向LSTM (batch_first=True):")
print(f"output shape: {output.shape}")  # (16, 150, 64)
print(f"hn shape: {hn.shape}")          # (2, 16, 64)
print(f"cn shape: {cn.shape}")          # (2, 16, 64)

# 验证 output 的最后一个时间步与 hn 的最后一层相同
print(f"output[:, -1, :] == hn[-1]: {torch.allclose(output[:, -1, :], hn[-1])}")



多层单向LSTM (batch_first=True):
output shape: torch.Size([16, 150, 64])
hn shape: torch.Size([2, 16, 64])
cn shape: torch.Size([2, 16, 64])
output[:, -1, :] == hn[-1]: True


#### 总结：
【前提：batch_first=True】
output,(hn,cn) = lstm(input,(h0,c0))

    由于
    output(序列长度, 批次大小, 隐藏维度×方向数)：返回最后一层，所有时间步的隐藏状态
    hn(层数×方向数, 批次大小, 隐藏维度)：返回所有层的最后一个时间步的隐藏状态

所以,在多层单向LSTM中,输出的最后一个时间步与隐藏状态的最后一层相同。即：
    output[:,-1,:] = hn[-1,:,:] != hn[0]

    1.lstm层数只会改变h0、c0、hn、cn这些隐藏状态和细胞状态的维度,而不会改变output的维度。
    

#### 3.单层双向LSTM
双向LSTM通过增加一个从序列末尾向开头处理的反向LSTM，能够同时捕捉前后文信息

In [17]:
import torch
import torch.nn as nn

# 定义参数
input_size = 3   # 每个时间步输入特征维度为3
seq_len = 150       # 序列长度为150
batch_size = 16    # 批次大小为16
hidden_size = 64  # 隐藏层特征维度为64
num_layers = 1  # 1层LSTM
num_directions = 2 # 双向，方向数为2

# 创建单层双向LSTM
lstm = nn.LSTM(input_size, hidden_size, num_layers, bidirectional=True)  # 双向LSTM

# 准备输入数据 input(序列长度, 批次大小, 输入特征维度)
input = torch.randn(seq_len, batch_size, input_size)  # (150, 16, 3)
# 初始化隐藏状态和细胞状态 h0,c0(层数×方向数, 批次大小, 隐藏维度)
h0 = torch.randn(num_layers * num_directions, batch_size, hidden_size)  # (1*2, 16, 64)
c0 = torch.randn(num_layers * num_directions, batch_size, hidden_size)

# 前向传播  output(序列长度, 批次大小, 隐藏维度×方向数)
output, (hn, cn) = lstm(input, (h0, c0))

print(f"\n单层双向LSTM:")
print(f"output shape: {output.shape}") # (150, 16, 64*2) 因为是双向LSTM，每个时间步的输出是正向和反向的拼接
print(f"hn shape: {hn.shape}")         # (1*2, 16, 64) 两个方向的最后隐藏状态(前者hn[0,:,:]是正向最后隐藏状态，后者hn[1,:,:]是反向最后隐藏状态)
print(f"cn shape: {cn.shape}")         # (1*2, 16, 64) 两个方向的最后记忆状态

# 验证 output 最后一个时间步的前半部分对应正向LSTM的最后隐藏状态，第一个时间步的后半部分对应反向LSTM的最后隐藏状态
print(torch.allclose(output[-1, :, :hidden_size], hn[0])) # 正向最后时间步
print(torch.allclose(output[0, :, hidden_size:], hn[1]))  # 反向最后时间步 (注意是0位置)


单层双向LSTM:
output shape: torch.Size([150, 16, 128])
hn shape: torch.Size([2, 16, 64])
cn shape: torch.Size([2, 16, 64])
True
True


#### batch_first = True

In [18]:
# 创建单层双向LSTM (batch_first=True)
lstm = nn.LSTM(input_size, hidden_size, num_layers, 
                    bidirectional=True, batch_first=True)  # 将模型的input和output的batch_size参数前置

# 准备输入数据 input(批次大小, 序列长度, 输入特征维度)
input = torch.randn(batch_size, seq_len, input_size)  # (16, 150, 3)
# 初始化隐藏状态和细胞状态 h0,c0(层数×方向数, 批次大小, 隐藏维度)
h0 = torch.randn(num_layers * num_directions, batch_size, hidden_size)  # (1*2, 16, 64)
c0 = torch.randn(num_layers * num_directions, batch_size, hidden_size)

# 前向传播  output(批次大小, 序列长度, 隐藏维度×方向数) 
output, (hn, cn) = lstm(input, (h0, c0))

print(f"\n单层双向LSTM (batch_first=True):")
print(f"output shape: {output.shape}")  # (16, 150, 64*2)
print(f"hn shape: {hn.shape}")          # (1*2, 16, 64)
print(f"cn shape: {cn.shape}")          # (1*2, 16, 64)

# 验证双向LSTM的输出关系
# output的最后一个时间步的前半部分 对应 正向LSTM的最后隐藏状态
# output的第一个时间步的后半部分 对应 反向LSTM的最后隐藏状态
print(f"正向验证: {torch.allclose(output[:, -1, :hidden_size], hn[0])}")  # hn[0]是正向LSTM的最后隐藏状态
print(f"反向验证: {torch.allclose(output[:, 0, hidden_size:], hn[1])}")  # hn[1]是反向LSTM的最后隐藏状态


单层双向LSTM (batch_first=True):
output shape: torch.Size([16, 150, 128])
hn shape: torch.Size([2, 16, 64])
cn shape: torch.Size([2, 16, 64])
正向验证: True
反向验证: True


#### 注意：
【前提：batch_first = True】
output(序列长度, 批次大小, 隐藏维度×方向数)：双向LSTM，每个时间步的输出是正向和反向的拼接。

    其中，output[:, -1, :hidden_size] 对应 output 最后一个时间步的前半部分，即正向LSTM的最后隐藏状态。
    其中，output[:, 0, hidden_size:] 对应 output 第一个时间步的后半部分，即反向LSTM的最后隐藏状态。
hn(层数×方向数, 批次大小, 隐藏维度)：双向LSTM，需要手动拼接

    前者hn[-2,:,:]是最后一层 正向最后隐藏状态，
    后者hn[-1,:,:]是最后一层 反向最后隐藏状态

    1.lstm层数只会改变h0、c0、hn、cn这些隐藏状态和细胞状态的维度,而不会改变output的维度。
    2.而方向数会改变output+h0、c0、hn、cn的维度


#### 4.多层双向LSTM
多层双向LSTM结合了深度结构和双向处理的优势，能捕捉更复杂的序列依赖关系

In [30]:
import torch
import torch.nn as nn

# 定义参数
input_size = 3   # 每个时间步输入特征维度为3
seq_len = 150       # 序列长度为150
batch_size = 16    # 批次大小为16
hidden_size = 64  # 隐藏层特征维度为64
num_layers = 2  # 2层LSTM
num_directions = 2 # 双向，方向数为2

# 创建多层双向LSTM
lstm = nn.LSTM(input_size, hidden_size, num_layers, bidirectional=True)

# 准备输入数据 input(序列长度, 批次大小, 输入特征维度)
input = torch.randn(seq_len, batch_size, input_size)  # (150, 16, 3)
# 初始化隐藏状态和细胞状态 h0,c0(层数×方向数, 批次大小, 隐藏维度)
h0 = torch.randn(num_layers * num_directions, batch_size, hidden_size)  # (2*2, 16, 64)
c0 = torch.randn(num_layers * num_directions, batch_size, hidden_size)

# 前向传播  output(序列长度, 批次大小, 隐藏维度×方向数)
output, (hn, cn) = lstm(input, (h0, c0))

print(f"\n多层双向LSTM:")
print(f"output shape: {output.shape}") # (150, 16, 64*2)
print(f"hn shape: {hn.shape}")         # (2*2, 16, 64) # 2层 * 2方向 = 4
print(f"cn shape: {cn.shape}")         # (2*2, 16, 64) 

# 验证双向LSTM的输出关系
# output的最后一个时间步的前半部分 对应 正向LSTM的最后隐藏状态
# output的第一个时间步的后半部分 对应 反向LSTM的最后隐藏状态
print("验证双向LSTM的输出关系:")
print("output的最后一个时间步的前半部分 对应 正向LSTM的最后隐藏状态:", 
      torch.allclose(output[-1, :, :hidden_size], hn[-2, :, :]))  # 最后一层正向LSTM的最后隐藏状态 hn[-2, :, :] = hn[2]
print("output的第一个时间步的后半部分 对应 反向LSTM的最后隐藏状态:", 
      torch.allclose(output[0, :, hidden_size:], hn[-1, :, :]))  # 最后一层反向LSTM的最后隐藏状态 hn[-1, :, :] = hn[3]



多层双向LSTM:
output shape: torch.Size([150, 16, 128])
hn shape: torch.Size([4, 16, 64])
cn shape: torch.Size([4, 16, 64])
验证双向LSTM的输出关系:
output的最后一个时间步的前半部分 对应 正向LSTM的最后隐藏状态: True
output的第一个时间步的后半部分 对应 反向LSTM的最后隐藏状态: True


#### batch_first=True

In [32]:
# 创建多层双向LSTM
lstm = nn.LSTM(input_size, hidden_size, num_layers, bidirectional=True, batch_first=True) 

# 准备输入数据 input(批次大小,序列长度,输入特征维度)
input = torch.randn(batch_size, seq_len, input_size)  # (16, 150, 3)
# 初始化隐藏状态和细胞状态 h0,c0(层数×方向数, 批次大小, 隐藏维度)
h0 = torch.randn(num_layers * num_directions, batch_size, hidden_size)  # (2*2, 16, 64)
c0 = torch.randn(num_layers * num_directions, batch_size, hidden_size)

# 前向传播  output(批次大小, 序列长度, 隐藏维度×方向数)
output, (hn, cn) = lstm(input, (h0, c0))

print(f"\n多层双向LSTM (batch_first=True):")
print(f"output shape: {output.shape}")  # (16, 150, 64*2)
print(f"hn shape: {hn.shape}")          # (2*2, 16, 64)
print(f"cn shape: {cn.shape}")          # (2*2, 16, 64)


# 验证双向LSTM的输出关系
# 验证双向LSTM的输出是否正确
print("output的最后一个时间步的前半部分 对应 正向LSTM的最后隐藏状态:", 
      torch.allclose(output[:, -1, :hidden_size], hn[-2, :, :]))  # 最后一层正向LSTM的最后隐藏状态 hn[-2, :, :] = hn[2]
print("output的第一个时间步的后半部分 对应 反向LSTM的最后隐藏状态:", 
      torch.allclose(output[:, 0, hidden_size:], hn[-1, :, :]))  # 最后一层反向LSTM的最后隐藏状态 hn[-1, :, :] = hn[3]


多层双向LSTM (batch_first=True):
output shape: torch.Size([16, 150, 128])
hn shape: torch.Size([4, 16, 64])
cn shape: torch.Size([4, 16, 64])
output的最后一个时间步的前半部分 对应 正向LSTM的最后隐藏状态: True
output的第一个时间步的后半部分 对应 反向LSTM的最后隐藏状态: True


#### 总结：
output(批次大小, 序列长度, 隐藏维度×方向数)：无论多少层的双向LSTM，输出的都是最后一层的每个时间步的隐藏状态，且每个时间步的隐藏状态是前向和后向的拼接。

    其中，output[:, -1, :hidden_size] 对应 output 最后一个时间步的前半部分，即正向LSTM的最后隐藏状态。
    其中，output[:, 0, hidden_size:] 对应 output 第一个时间步的后半部分，即反向LSTM的最后隐藏状态。
hn(层数×方向数, 批次大小, 隐藏维度)：双向LSTM，最后一层的正向最后隐藏状态和反向最后隐藏状态需要手动拼接。
    
    其中，hn[-2,:,:] 对应 最后一层 正向最后隐藏状态。
    其中，hn[-1,:,:] 对应 最后一层 反向最后隐藏状态。


例如：由于是两层双向LSTM，所以hn的形状是(层数×方向数, 批次大小, 隐藏维度)，即(2*2, 16, 64)

    其中，hn[0,:,:] 对应 第一层lstm 正向最后隐藏状态。
    其中，hn[1,:,:] 对应 第一层lstm 反向最后隐藏状态。
    其中，hn[2,:,:] 对应 第二层lstm 正向最后隐藏状态。同时也是 最后一层lstm 正向最后隐藏状态，即hn[-2,:,:]
    其中，hn[3,:,:] 对应 第二层lstm 反向最后隐藏状态。同时也是 最后一层lstm 反向最后隐藏状态，即hn[-1,:,:]

所以，可以得出：无论lstm有多少层，都可以通过hn[-2,:,:]和hn[-1,:,:]来获取最后一层lstm的正向最后隐藏状态和反向最后隐藏状态。

    最后一层lstm 正向最后隐藏状态 = hn[-2,:,:] 等价于 output[:, -1, :hidden_size] (前提batch_first=True)
    最后一层lstm 反向最后隐藏状态 = hn[-1,:,:] 等价于 output[:, 0, hidden_size:]

#### 上面的例子都是在处理等长的序列，那么如果序列长度不同，该怎么办？
接下来再加一个条件，即在batch_first=True的条件上，通过nn.utils.rnn.pack_padded_sequence打包来处理变长序列（序列分类任务，无需解包），请分别将4种不同LSTM结构示例代码重新返回一下，注意：每种例子要分别给出两个实现方案（方案一：通过hidden直接取隐藏状态；方案二：通过output取每个序列的最后一个有效输出）

### 1.单层单向LSTM（batch_first=True+pack_padded_sequence）

#### 基础设置

In [ ]:
import torch
import torch.nn as nn
from torch.nn.utils.rnn import pack_padded_sequence, pad_packed_sequence

# 定义参数
input_size = 5  # 输入特征维度
hidden_size = 64  # 隐藏层神经元数量
batch_size = 3  # 批次大小
max_seq_len = 10  # 最大序列长度

# 创建变长序列数据(就模拟生成了3条序列，这里就当batch_size=3)
sequences = [
    torch.randn(9, input_size),  # 长度9
    torch.randn(8, input_size),  # 长度8
    torch.randn(10, input_size)   # 长度10
]

# 实际长度
lengths = torch.tensor([9, 8, 10], dtype=torch.long)  # 序列长度一般设置长整型(int64)

# 填充序列 (batch_first=True)  # pad_sequence返回一个B x T x * 的Tensor，其中T是最长序列的长度。
padded_sequences = torch.nn.utils.rnn.pad_sequence(
    [seq for seq in sequences], batch_first=True, padding_value=0.0
)

print(f"填充后序列形状: {padded_sequences.shape}")  # (3, 10, 5)
padded_sequences

填充后序列形状: torch.Size([3, 10, 5])


tensor([[[-0.2942,  1.4037, -0.1995, -1.9906, -0.2764],
         [-0.5374,  0.6689, -0.0811,  1.4272, -0.9046],
         [ 0.1317,  0.4717, -0.1347, -0.5275, -0.7219],
         [-0.2062, -0.0530,  0.3761, -0.2642, -0.2805],
         [-1.1988,  0.6610, -0.1231,  1.4031, -0.4455],
         [-1.3469, -0.0526, -0.5192, -0.2550, -1.7234],
         [ 1.2302, -0.2976, -0.8181, -0.3423, -0.2701],
         [ 0.7061, -0.8825, -0.9025,  0.0543, -0.6199],
         [ 0.6773, -2.0237,  1.1781,  0.8221,  0.3204],
         [ 0.0000,  0.0000,  0.0000,  0.0000,  0.0000]],

        [[ 0.2366,  1.3393, -0.3493, -0.1392,  1.1625],
         [ 1.5315,  0.9538, -0.5492, -1.5213,  0.1679],
         [-0.3589,  0.4066,  0.6850,  0.5801,  0.4694],
         [ 0.0481,  0.5873, -0.3045, -0.7144, -0.0753],
         [-0.1744, -1.1870,  0.3697, -0.0852, -1.7413],
         [ 0.7110, -0.3730,  0.5228, -0.4659,  0.2233],
         [-0.3938,  1.8047,  1.3562, -0.8301, -0.0579],
         [ 0.8016, -0.5574, -0.4324, -0.4115, 

#### 方案一：通过hidden取最后一层lstm的 最后一个时间步的隐藏状态

In [ ]:
# 创建单层单向LSTM
lstm = nn.LSTM(input_size, hidden_size, num_layers=1, batch_first=True)  # batch_first=True

# 按长度降序排序
lengths_sorted, sorted_idx = torch.sort(lengths, descending=True)  # 对序列长度进行降序排序，返回排序后的长度和索引
sequences_sorted = padded_sequences[sorted_idx]  # 使用排序后的索引对填充序列进行排序

# 打包序列以处理变长序列
packed_input = pack_padded_sequence(
    sequences_sorted,  # 按长度降序排序后的序列 形状(3,10,5)
    lengths_sorted.cpu(),  # 按长度降序排序后的长度 [10,9,8]，注意：如果以tensor形式提供，则必须在CPU上
    batch_first=True)

'''
正常的input(批次大小, 序列长度, 输入特征维度)
打包后的input：是一个PackedSequence对象（注意：所有RNN模块都接受已打包序列作为输入）
PackedSequence对象包含两个主要属性：
    data：包含所有有效（非填充）元素的张量  形状(8+9+10,5)
    batch_sizes：每个时间步的有效序列数量  [3, 3, 3, 3, 3, 3, 3, 3, 2, 1] 三维横截面
'''

# 前向传播
packed_output, (hn, cn) = lstm(packed_input)  # 如果不给初始状态h0和c0，默认初始状态为0

'''
正常的output(批次大小, 序列长度, 隐藏维度×方向数)
打包后的lstm前向传播输出的output：是一个PackedSequence对象
PackedSequence对象包含两个主要属性：
    data：包含所有有效（非填充）元素的张量  形状(27,64) 64是隐藏维度
    batch_sizes：每个时间步的有效序列数量  [3, 3, 3, 3, 3, 3, 3, 3, 2, 1] 三维思维

但是无论打不打包，hn都是每个序列最后一个有效时间步的隐藏状态，形状为(层数×方向数, 批次大小, 隐藏维度)
'''

# hn(层数×方向数, 批次大小, 隐藏维度)
print("单层单向LSTM - 方案一 (通过hidden取隐藏状态):")
print(f"hn shape: {hn.shape}")  # (1*1,3,64)
print(f"取最后一层隐藏状态(还未恢复顺序): {hn[-1].shape}")  # (3, 64)

# 恢复原始顺序（根据排序后索引）
_, unsorted_indices = torch.sort(sorted_idx)  # 降序

# 取最后一层的隐藏状态，再根据原始索引恢复顺序
final_hidden = hn[-1][unsorted_indices]
print(f"恢复顺序后: {final_hidden.shape}")

单层单向LSTM - 方案一 (通过hidden取隐藏状态):
hn shape: torch.Size([1, 3, 64])
取最后一层隐藏状态(还未恢复顺序): torch.Size([3, 64])
恢复顺序后: torch.Size([3, 64])


测试：torch.sort()方法 注意区分 numpy.argsort()和numpy.sort()

torch.sort(input, dim=-1, descending=False, *, stable=False, out=None)：按值对 input 张量沿给定维度进行升序排序。如果未指定 `dim`，则选择 `input` 的最后一个维度。如果 descending 为 True，则按值降序排序。如果 stable 为 True，则排序例程将变为稳定排序，保留等价元素的顺序。

    参数：
        input (Tensor) – 输入张量。
        dim (int, optional) – 要沿其排序的维度
        descending (bool, optional) – 控制排序顺序（升序或降序）
    关键字参数：
        stable (bool, optional) – 使排序例程稳定，保证等价元素的顺序得以保留。
        out (tuple, optional) – 可选的输出元组 (Tensor, LongTensor)，可用于作为输出缓冲区
    返回：
        一个 namedtuple，包含 (values, indices)，其中 values 是排序后的值，indices 是原始 input 张量中元素的索引。


In [79]:
import torch
x = torch.randn(3, 4)  # 3行4列的随机张量
torch.sort(x)  # 默认按行排序(默认升序),返回排序后的张量和排序后的索引

torch.return_types.sort(
values=tensor([[ 0.1677,  0.6362,  0.6980,  1.1409],
        [-1.7644, -0.4963, -0.1562,  0.6848],
        [-0.5681, -0.1070, -0.0169,  0.8507]]),
indices=tensor([[3, 2, 1, 0],
        [2, 0, 1, 3],
        [1, 0, 2, 3]]))

In [82]:
torch.sort(x, dim=1, descending=True)  # 按行降序排序,返回排序后的张量和排序后的索引

torch.return_types.sort(
values=tensor([[ 1.1409,  0.6980,  0.6362,  0.1677],
        [ 0.6848, -0.1562, -0.4963, -1.7644],
        [ 0.8507, -0.0169, -0.1070, -0.5681]]),
indices=tensor([[0, 1, 2, 3],
        [3, 1, 0, 2],
        [3, 2, 0, 1]]))

#### 方案二：通过 output 取每个序列的最后一个有效输出

In [ ]:
# 创建单层单向LSTM（同上）
lstm = nn.LSTM(input_size, hidden_size, num_layers=1, batch_first=True)

# 排序和打包（同上）
lengths_sorted, sorted_idx = lengths.sort(descending=True)
sequences_sorted = padded_sequences[sorted_idx]
packed_input = pack_padded_sequence(sequences_sorted, lengths_sorted.cpu(), batch_first=True)

# 前向传播（同上）
packed_output, (hn, cn) = lstm(packed_input)  # 如果不给初始状态h0和c0，默认初始状态为0
'''
正常的output(批次大小, 序列长度, 隐藏维度×方向数)
打包后的lstm前向传播输出的output：是一个PackedSequence对象
PackedSequence对象包含两个主要属性：
    data：包含所有有效（非填充）元素的张量  形状(27,64) 64是隐藏维度
    batch_sizes：每个时间步的有效序列数量  [3, 3, 3, 3, 3, 3, 3, 3, 2, 1] 三维思维
'''
# 解包：返回填充后的输出张量output、每个序列的实际长度的张量output_lengths
output, output_lengths = pad_packed_sequence(packed_output, batch_first=True)

print("单层单向LSTM - 方案二 (通过output取最后一个有效输出):")
print(f"解包后output shape: {output.shape}")  # (3, 10, 64)  output(批次大小, 序列长度, 隐藏维度×方向数)

# 手动取每个序列的最后一个有效输出
last_outputs = []
for i, length in enumerate(output_lengths):
    last_outputs.append(output[i, length-1, :])

# stack()函数将列表中的张量按指定维度拼接起来
last_outputs = torch.stack(last_outputs)  # (批次大小, 隐藏维度×方向数)-> (3, 64)

# 获取原始顺序（根据排序后索引）
_, unsorted_indices = torch.sort(sorted_idx)

# 取最后一层的隐藏状态，再根据原始索引恢复顺序
final_output = last_outputs[unsorted_indices]
print(f"最后一个有效输出: {final_output.shape}")  # (3, 64)

# 验证两种方案结果相同
print(f"两种方案结果相同: {torch.allclose(final_hidden, final_output, atol=1e-6)}")

单层单向LSTM - 方案二 (通过output取最后一个有效输出):
解包后output shape: torch.Size([3, 10, 64])
最后一个有效输出: torch.Size([3, 64])
两种方案结果相同: False
