### MockDataClient._simulate_crw_path()

    heading = np.radians(heading_deg)  # 初始航向角度 (弧度)
    
    老师讲解：这里使用np.radians()函数将角度从度转换为弧度。为什么需要转换呢？
    数学原理：
        在Python的数学计算中，三角函数（sin, cos）使用弧度制
        转换公式：弧度 = 角度 × π / 180
        例如：90度 = 90 × π / 180 = π/2 ≈ 1.5708弧度

    speed_deg = (speed_knots * 1.852) / 111.0   # 每小时移动的角度 (弧度)
    
    老师讲解：这是最复杂但最重要的转换！我们来分步理解：
        1.节 → 公里/小时：speed_knots * 1.852
            1节 = 1海里/小时 = 1.852公里/小时
        2.公里/小时 → 纬度/经度变化率：÷ 111.0
            为什么是111.0？这是地球的近似换算系数
            在赤道上，1度经度 ≈ 111公里
            1度纬度 ≈ 111公里（变化很小）
            因此：每小时移动的角度 = 速度(公里/小时) ÷ 111
        3.注意：严格来说，经度的实际距离随纬度变化，但这里做了简化

    lat += speed_deg * np.cos(heading)  # 纬度变化
    lon += speed_deg * np.sin(heading)  # 经度变化

    老师讲解：这是根据航向计算位置变化的公式：
    地理坐标移动原理：
        1.np.cos(heading)：获取南北方向分量（纬度变化）
            heading=0°（正北）：cos(0)=1，向北移动
            heading=180°（正南）：cos(180)=-1，向南移动

        2.np.sin(heading)：获取东西方向分量（经度变化）
            heading=90°（正东）：sin(90)=1，向东移动
            heading=270°（正西）：sin(270)=-1，向西移动

    新纬度 = 旧纬度 + (每小时移动度数 × cos(航向))
    新经度 = 旧经度 + (每小时移动度数 × sin(航向))

    noise = np.radians(np.random.normal(0, turn_rate))  # 随机转向角度 (弧度)
    heading += noise  # 更新航向角度

    老师讲解：这是实现随机游走的关键部分！
        1.生成随机噪声：
            np.random.normal(0, turn_rate)：从正态分布中随机采样
            均值=0，标准差=turn_rate（默认为5.0度）
            例如：可能产生-3.2°、+4.7°、+0.5°等随机值
        2.转换为弧度：np.radians()将角度转换为弧度
        3.更新航向：将随机噪声加到当前航向上
            这使得每次移动后航向都有轻微随机变化
            turn_rate越大，轨迹越曲折；越小，轨迹越直

In [5]:
#!/usr/bin/env python3
# -*- coding: UTF-8 -*-

class User(object):
    def __new__(cls, *args, **kwargs):
        # 打印 __new__方法中的相关信息
        print('调用了 def __new__ 方法')
        print(args)
        # 最后返回父类的方法
        return super(User, cls).__new__(cls)

    def __init__(self, name, age):
        print('调用了 def __init__ 方法')
        self.name = name
        self.age = age

    def _get_name(self):
        print('调用了 def _get_name 方法')
        return self.name
    
    def get_age(self):
        print('调用了 def get_age 方法')
        return self.age


if __name__ == '__main__':
    usr = User('两点水', 23)

In [2]:
import time

class Timer:
    def __enter__(self):
        self.start = time.time()
        return self  # 返回的对象会给到 as 后面的变量

    def __exit__(self, exc_type, exc_val, exc_tb):
        # exc_type 不为 None 说明代码块里报错了
        end = time.time()
        print(f"⏱️ 代码块执行耗时: {end - self.start:.4f} 秒")
        # 返回 True 可以吞掉异常，返回 False (默认) 会抛出异常
        return False 

# 使用场景
with Timer():
    # 这里是你的业务代码
    time.sleep(1)
    print("任务完成")

任务完成
⏱️ 代码块执行耗时: 1.0079 秒


In [1]:
class SmartConfig:
    def __init__(self):
        self._config = {"db": "mysql", "port": 3306}

    def __getitem__(self, key):
        print(f"正在从配置中心读取: {key}")
        return self._config.get(key, "Default")

    def __setitem__(self, key, value):
        print(f"正在更新配置中心: {key} = {value}")
        self._config[key] = value
        
    def __len__(self):
        return len(self._config)

conf = SmartConfig()
print(conf['db'])      # 触发 __getitem__
conf['timeout'] = 30   # 触发 __setitem__

正在从配置中心读取: db
mysql
正在更新配置中心: timeout = 30


In [1]:
#!/usr/bin/env python3
# -*- coding: UTF-8 -*-
import time

class VirtualServer(object):
    """
    一个模拟云服务器的类，集成了 Python 核心魔术方法
    """

    # ==========================================
    # 1. 创世纪：构造与初始化
    # ==========================================
    def __new__(cls, hostname, cpu_cores, ram_gb):
        print(f"\n[1. __new__] 正在申请内存，创建 '{hostname}' 的肉身...")
        # 真正创建对象实例
        instance = super(VirtualServer, cls).__new__(cls)
        return instance

    def __init__(self, hostname, cpu_cores, ram_gb):
        print(f"[2. __init__] 对象已生成，正在初始化属性 (Hostname: {hostname})...")
        # 这里会触发 __setattr__，要注意！
        self.hostname = hostname
        self.cpu_cores = cpu_cores
        self.ram_gb = ram_gb
        self.storage = {} # 模拟文件系统
        self.status = "stopped"

    # ==========================================
    # 2. 颜值系：字符串表示
    # ==========================================
    def __str__(self):
        # 用户视角的友好展示
        return f"🖥️ [Server: {self.hostname}] CPU:{self.cpu_cores}C RAM:{self.ram_gb}G"

    def __repr__(self):
        # 开发者视角的代码重现
        return f"VirtualServer(hostname='{self.hostname}', cpu_cores={self.cpu_cores}, ram_gb={self.ram_gb})"

    # ==========================================
    # 3. 管家系：属性访问控制 (最核心、最危险的部分)
    # ==========================================
    def __getattribute__(self, item):
        # ⚠️ 注意：每次访问任何属性（包括 self.hostname）都会先经过这里
        # 为了避免无限递归，必须调用父类的方法来获取属性
        # print(f"  -> [监控] 正在尝试访问属性: {item}") # 打开这行会刷屏，调试时小心
        return super().__getattribute__(item)

    def __setattr__(self, key, value):
        print(f"[3. __setattr__] 拦截赋值: {key} = {value}")
        if key == 'cpu_cores' and value <= 0:
            raise ValueError("CPU 核心数必须为正数！")
        
        # ⚠️ 绝对不能写 self.key = value，否则死循环
        self.__dict__[key] = value

    def __getattr__(self, item):
        # 只有属性找不到时，才会来这里（最后的救命稻草）
        print(f"[4. __getattr__] 警告：属性 '{item}' 不存在！启动动态补救机制...")
        if item.startswith("install_"):
            software = item.split("_")[1]
            return lambda: f"正在自动安装软件: {software}..."
        raise AttributeError(f"Server really doesn't have '{item}'")

    # ==========================================
    # 4. 容器系：像字典一样操作 (模拟文件存储)
    # ==========================================
    def __setitem__(self, key, value):
        print(f"[5. __setitem__] 写入文件: {key}, 大小: {value}MB")
        self.storage[key] = value

    def __getitem__(self, key):
        print(f"[5. __getitem__] 读取文件: {key}")
        return self.storage.get(key, 0)

    def __len__(self):
        print(f"[5. __len__] 统计文件数量")
        return len(self.storage)

    # ==========================================
    # 5. 比较系：服务器性能PK
    # ==========================================
    def __eq__(self, other):
        print("[6. __eq__] 判断两台服务器是否规格相同")
        if isinstance(other, VirtualServer):
            return self.cpu_cores == other.cpu_cores and self.ram_gb == other.ram_gb
        return False

    def __gt__(self, other):
        print("[6. __gt__] 判断当前服务器性能是否更强")
        if isinstance(other, VirtualServer):
            return self.cpu_cores > other.cpu_cores
        return NotImplemented

    # ==========================================
    # 6. 函数系：对象当函数用
    # ==========================================
    def __call__(self, command):
        print(f"[7. __call__] 收到指令，正在执行: {command}")
        return f"Exec Success: {command}"

    # ==========================================
    # 7. 上下文管理：with 语句
    # ==========================================
    def __enter__(self):
        print("\n[8. __enter__] 进入维护模式 (Maintenance Mode)...")
        self.original_status = self.status
        self.status = "maintenance"
        return self

    def __exit__(self, exc_type, exc_val, exc_tb):
        print(f"[8. __exit__] 退出维护模式。恢复状态: {self.original_status}")
        self.status = self.original_status
        # 如果代码块里报错，exc_type 就不是 None。返回 True 可以吞掉异常。
        if exc_type:
            print(f"    捕获到异常: {exc_val} (但我决定处理它，不让程序崩溃)")
            return True 

    # ==========================================
    # 8. 终结者：析构函数
    # ==========================================
    def __del__(self):
        print(f"[9. __del__] 服务器 '{self.hostname}' 下线，资源回收完毕。")


# ==============================================================================
#   开始你的调试之旅！(请在下面每一行都打断点)
# ==============================================================================

if __name__ == '__main__':
    print("=== 阶段一：诞生 ===")
    # 触发 __new__ -> __init__ -> __setattr__
    v1 = VirtualServer("Web-Server-01", 4, 16)
    
    print("\n=== 阶段二：展示 ===")
    # 触发 __str__
    print(f"普通打印: {v1}")
    # 触发 __repr__
    print(f"调试打印: {repr(v1)}")

    print("\n=== 阶段三：属性魔法 ===")
    # 触发 __getattribute__ (每次访问都会触发)
    _ = v1.status 
    
    # 触发 __setattr__
    v1.cpu_cores = 8 
    
    # 触发 __getattr__ (访问不存在的 install_nginx)
    # 因为我们在 __getattr__ 里动态返回了一个函数，所以这里可以直接调用
    print(v1.install_nginx()) 

    print("\n=== 阶段四：容器模拟 ===")
    # 触发 __setitem__
    v1["/var/log/syslog"] = 500 
    v1["/home/user/data"] = 1024
    # 触发 __getitem__
    print(f"日志文件大小: {v1['/var/log/syslog']} MB")
    # 触发 __len__
    print(f"当前文件总数: {len(v1)}")

    print("\n=== 阶段五：像函数一样调用 ===")
    # 触发 __call__
    result = v1("sudo apt-get update")
    print(result)

    print("\n=== 阶段六：比较 ===")
    v2 = VirtualServer("DB-Server-01", 16, 64)
    # 触发 __gt__
    if v2 > v1:
        print(f"{v2.hostname} 性能强于 {v1.hostname}")
    # 触发 __eq__
    if v1 != v2:
        print("两台服务器规格不同")

    print("\n=== 阶段七：上下文管理 (with) ===")
    # 触发 __enter__
    with v1 as s:
        print(f"   当前状态: {s.status}")
        print("   正在执行危险的维护操作...")
        # 模拟一个异常，触发 __exit__ 的异常处理逻辑
        raise RuntimeError("硬盘故障！") 
    # 触发 __exit__
    
    print(f"\n检查退出后状态: {v1.status}")

    print("\n=== 阶段八：销毁 ===")
    # 手动删除引用，触发 __del__
    del v1
    del v2
    print("=== 程序结束 ===")

=== 阶段一：诞生 ===

[1. __new__] 正在申请内存，创建 'Web-Server-01' 的肉身...
[4. __getattr__] 警告：属性 '__iter__' 不存在！启动动态补救机制...
[4. __getattr__] 警告：属性 'hostname' 不存在！启动动态补救机制...
[4. __getattr__] 警告：属性 '__iter__' 不存在！启动动态补救机制...
[4. __getattr__] 警告：属性 'hostname' 不存在！启动动态补救机制...
[4. __getattr__] 警告：属性 '__iter__' 不存在！启动动态补救机制...
[4. __getattr__] 警告：属性 'hostname' 不存在！启动动态补救机制...
[4. __getattr__] 警告：属性 '__iter__' 不存在！启动动态补救机制...
[4. __getattr__] 警告：属性 'hostname' 不存在！启动动态补救机制...
[4. __getattr__] 警告：属性 'hostname' 不存在！启动动态补救机制...
[4. __getattr__] 警告：属性 'hostname' 不存在！启动动态补救机制...
[4. __getattr__] 警告：属性 'hostname' 不存在！启动动态补救机制...
[4. __getattr__] 警告：属性 'hostname' 不存在！启动动态补救机制...
[4. __getattr__] 警告：属性 'hostname' 不存在！启动动态补救机制...
[4. __getattr__] 警告：属性 'hostname' 不存在！启动动态补救机制...
[4. __getattr__] 警告：属性 'hostname' 不存在！启动动态补救机制...
[4. __getattr__] 警告：属性 'hostname' 不存在！启动动态补救机制...
[4. __getattr__] 警告：属性 'hostname' 不存在！启动动态补救机制...
[4. __getattr__] 警告：属性 'hostname' 不存在！启动动态补救机制...
[4. __getattr__] 警告：属性 'hostname' 不存在！

In [1]:
class Hello(object):
    def hello(self, name='Py'):
        print('Hello,', name)

h = Hello()
h.hello()

print(type(Hello))
print(type(h))

Hello, Py
<class 'type'>
<class '__main__.Hello'>


In [2]:
def printHello(self, name='Py'):
    # 定义一个打印 Hello 的函数
    print('Hello,', name)

# type(类名, 父类的元组（针对继承的情况，可以为空），包含属性的字典（名称和值）)
Hello = type('Hello', (object,), dict(hello=printHello))

# 实例化 Hello 类
h = Hello()
# 调用 Hello 类的方法
h.hello()
# 查看 Hello class 的类型
print(type(Hello))
# 查看实例 h 的类型
print(type(h))

Hello, Py
<class 'type'>
<class '__main__.Hello'>


In [4]:
# 整形
age = 23
print(age.__class__)
# 字符串
name = '两点水'
print(name.__class__)


# 函数
def fu():
    pass


print(fu.__class__)


# 实例
class eat(object):
    pass


mEat = eat()

print(mEat.__class__)

print(age.__class__.__class__)
print(name.__class__.__class__)
print(fu.__class__.__class__)
print(mEat.__class__.__class__)

<class 'int'>
<class 'str'>
<class 'function'>
<class '__main__.eat'>
<class 'type'>
<class 'type'>
<class 'type'>
<class 'type'>


In [8]:
import numpy as np

data = np.random.poisson(lam=0.2, size=(10,15)).astype(float)  # 生成3x4的泊松分布数据  lam=0.2表示每个网格平均有0.2艘船
data

array([[0., 1., 1., 0., 0., 0., 0., 1., 1., 0., 0., 0., 1., 0., 1.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 1., 0., 2., 0., 1., 1.],
       [1., 0., 0., 0., 0., 1., 0., 0., 0., 3., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 2., 0., 0., 0., 2., 0., 0., 0., 1., 0., 0.],
       [1., 1., 0., 0., 1., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [ ]:
np.where(data > 0.5, 1.0, 0.0)  # 对大于0.5的信号进行二值化

array([[0., 1., 1., 0., 0., 0., 0., 1., 1., 0., 0., 0., 1., 0., 1.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 1., 0., 1., 0., 1., 1.],
       [1., 0., 0., 0., 0., 1., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 1., 0., 0., 0., 1., 0., 0.],
       [1., 1., 0., 0., 1., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [ ]:
import numpy as np
a = np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9]
])
np.where(a < 5, 1, a*10)  # 对小于5的值赋值为1，大于等于5的值乘以10

array([[ 1,  1,  1],
       [ 1, 50, 60],
       [70, 80, 90]])

In [ ]:
from numpy import random

x = random.poisson(lam=0.05, size=(15,20))

print(x)

[[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0]
 [0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 1 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 1 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0]
 [0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]]


In [34]:
from sklearn.cluster import DBSCAN
import numpy as np

x = np.array([
    [0,0],
    [1,1],
    [2,2],
    [3,3],
    [8,8]
])

clustering = DBSCAN(eps=1.42, min_samples=3).fit(x)
clustering.labels_

array([ 0,  0,  0,  0, -1], dtype=int64)

In [44]:
from sklearn.cluster import DBSCAN
import numpy as np

x = np.array([
    [0,0],[0,1],[0,2],
    [1,1],
    [2,2],
    [3,3],
    [8,8]
])

clustering = DBSCAN(eps=1, min_samples=4).fit(x)
clustering.labels_

array([ 0,  0,  0,  0, -1, -1, -1], dtype=int64)

In [45]:
from scipy.ndimage import uniform_filter1d

uniform_filter1d([1,2,3,4,5,6], size=3)

array([1, 2, 3, 4, 5, 5])

In [46]:
from scipy.ndimage import uniform_filter1d
import numpy as np

x = np.array([
    [1,2,3,4,5,6],
    [1,2,3,4,5,6],
    [1,2,3,4,5,6]
])
uniform_filter1d(x, size=3)

array([[1, 2, 3, 4, 5, 5],
       [1, 2, 3, 4, 5, 5],
       [1, 2, 3, 4, 5, 5]])

In [ ]:
from scipy.ndimage import uniform_filter
import numpy as np

x = np.array([
    [1,2,3,4,5,6],
    [1,2,3,4,5,6],
    [1,2,3,4,5,6]
])

uniform_filter(x, size=3)

array([[1, 2, 3, 4, 5, 5],
       [1, 2, 3, 4, 5, 5],
       [1, 2, 3, 4, 5, 5]])

In [70]:
from scipy.ndimage import uniform_filter
import numpy as np

x = np.array([
    [1,2,3,4],
    [5,6,7,8],
    [9,10,11,12]
])

uniform_filter(x, size=3)

array([[2, 3, 4, 4],
       [5, 6, 7, 7],
       [7, 8, 9, 9]])

In [68]:
import numpy as np
x = np.array([
    [1, 2, 3,4,5],
    [6, 7, 8,9,10],
    [11,12,13,14,15],
    [16,17,18,19,20],
    [21,22,23,24,25]
])

# 均值滤波
from scipy.ndimage import uniform_filter
y = uniform_filter(x, size=3,mode='reflect')

print(y)

[[ 2  3  4  5  5]
 [ 6  7  8  9  9]
 [11 12 13 14 14]
 [16 17 18 19 19]
 [19 20 21 22 22]]


In [2]:
line1 = "   Hello World!   \n"
cleaned_line1 = line1.strip()
print(f"原始字符串: '{line1}'")
print(f"处理后: '{cleaned_line1}'") # 输出: 'Hello World!'

line2 = "\t\tPython is fun\n"
cleaned_line2 = line2.strip()
print(f"原始字符串: '{line2}'")
print(f"处理后: '{cleaned_line2}'") # 输出: 'Python is fun'

原始字符串: '   Hello World!   
'
处理后: 'Hello World!'
原始字符串: '		Python is fun
'
处理后: 'Python is fun'


In [11]:
def my_decorator(func):
    print("my_decorator")  # 1
    def wrapper():  # 2
        print("Something is happening before the function is called.")  # 7
        func()  # 8
        print("Something is happening after the function is called.")  # 9

    print("wrapper")  # 3
    return wrapper  # 4

@my_decorator
def say_hello():  # 5
    # 1. 调用my_decorator()
    print("Hello!")  # 8

say_hello()  # 6

my_decorator
wrapper
Something is happening before the function is called.
Hello!
Something is happening after the function is called.


In [12]:
def fac(num):
    if num in (0, 1):
        return 1
    return num * fac(num - 1)

fac(5)

120

In [3]:
data = []

def print_(obj):

    data.append(obj)
    print(obj)

print_('hello')
print_('I love python')

data.append('Python closure')
print(data)

hello
I love python
['hello', 'I love python', 'Python closure']


In [3]:
def print_with_memory():
    data = []

    def inner(obj):
        data.append(obj)
        print(obj)

    # print_ = inner
    return inner

print_ = print_with_memory()

print_('hello')
print_('I love python')

print_.__closure__  # (<cell at 0x00000173FF716A00: list object at 0x00000173FF771C00>,)
print_.__closure__[0].cell_contents  # ['hello', 'I love python']

hello
I love python


['hello', 'I love python']

In [ ]:
def decorator(func):
    data = []

    def inner(obj):
        data.append(obj)
        func(obj)

    # print_ = inner
    return inner

print_ = decorator(print)

print_('hello')
print_('I love python')

print_.__closure__  # (<cell at 0x00000173FF716A00: list object at 0x00000173FF771C00>,)
print_.__closure__[0].cell_contents  # ['hello', 'I love python']

hello
I love python


['hello', 'I love python']

In [2]:
def decorator(func):
    data = []

    def inner(*args, **kwargs):
        data.append((args, kwargs))
        func(*args, **kwargs)

    # print_ = inner
    return inner

print_ = decorator(print)

print_('I love python')
print_(1,2,3)
print_(1,2,3,sep='--')
print_.__closure__[0].cell_contents

I love python
1 2 3
1--2--3


[(('I love python',), {}), ((1, 2, 3), {}), ((1, 2, 3), {'sep': '--'})]

In [ ]:
def decorator(func):
    data = []

    def inner(*args, **kwargs):
        data.append((args, kwargs))
        func(*args, **kwargs)  # 等价于 max(*args, **kwargs)

    # print_ = inner
    return inner

max_ = decorator(max)
print(max_(1,2,3))
print(max_('hello','byebye'))
print(max_(4,5,6,key=lambda x: -x))
max_.__closure__[0].cell_contents

None
None
None


[((1, 2, 3), {}),
 (('hello', 'byebye'), {}),
 ((4, 5, 6), {'key': <function __main__.<lambda>(x)>})]

In [6]:
def decorator(func):
    data = []

    def inner(*args, **kwargs):
        data.append((args, kwargs))
        result = func(*args, **kwargs)  # 等价于 max(*args, **kwargs)
        return result

    # print_ = inner
    return inner

max_ = decorator(max)
print(max_(1,2,3))
print(max_('hello','byebye'))
print(max_('aa','bbb','ccc',key=lambda x: len(str(x))))
max_.__closure__[0].cell_contents

3
hello
bbb


[((1, 2, 3), {}),
 (('hello', 'byebye'), {}),
 (('aa', 'bbb', 'ccc'), {'key': <function __main__.<lambda>(x)>})]

In [10]:
def decorator(func):
    data = []

    def inner(*args, **kwargs):
        data.append((args, kwargs))
        result = func(*args, **kwargs)  # 等价于 max(*args, **kwargs)
        return result

    # print_ = inner
    return inner

def my_special_func(name,repeat):
    return name.upper() * repeat

new_my_special_func = decorator(my_special_func)

print(new_my_special_func('hello',3))
print(new_my_special_func('world',2))
new_my_special_func.__closure__[0].cell_contents

HELLOHELLOHELLO
WORLDWORLD


[(('hello', 3), {}), (('world', 2), {})]

In [1]:
def decorator(func):

    def wrapper(*args, **kwargs):
        print("Before function call")
        func(*args, **kwargs)
        print("After function call")

    return wrapper

@decorator  # greet = decorator(greet)
def greet(name):
    print(f"Hello {name}!")

greet("World")

Before function call
Hello World!
After function call


In [4]:
def repeat(num_times):

    def decorator(func):

        def wrapper(*args, **kwargs):

            for _ in range(num_times):
                func(*args, **kwargs)

        return wrapper

    return decorator

@repeat(3)  # greet = repeat(3)(greet)
def greet(name):
    print(f"Hello {name}!")

greet("World")

print(greet.__closure__)
greet.__closure__[1].cell_contents


Hello World!
Hello World!
Hello World!
(<cell at 0x000002813CD5ED90: function object at 0x000002813CD71790>, <cell at 0x000002813CD5E070: int object at 0x0000028136F66970>)


3

In [ ]:
from functools import wraps

def decorator(func):

    @wraps(func)  # 保持原函数func的元数据
    def wrapper(*args, **kwargs):
        print("Before function call")
        func(*args, **kwargs)
        print("After function call")

    return wrapper

@decorator  # greet = decorator(greet)
def greet(name):
    print(f"Hello {name}!")

greet("World")